# tsqldump/test/Dockerfile.db

FROM mcr.microsoft.com/mssql/server:2022-latest

USER root
WORKDIR /usr/src/app

# Copy initialization SQL script
COPY init.sql .

# Environment variables required for startup
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Test_Password123!

# Expose port 1433
EXPOSE 1433

# Start SQL Server in background, wait for it to boot, run init.sql, then keep SQL running
CMD /bin/bash -c " \
    /opt/mssql/bin/sqlservr & \
    echo 'Waiting for SQL Server to boot...'; \
    until /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P '$MSSQL_SA_PASSWORD' \
        -C \
        -Q 'SELECT 1' \
            &> /dev/null; \
    do \
        sleep 1; \
    done; \
    echo 'Running init.sql script...'; \
    /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P '$MSSQL_SA_PASSWORD' \
        -C \
        -i /usr/src/app/init.sql; \
    echo 'Test database initialized!'; \
    wait \
    "

HEALTHCHECK --interval=5s --timeout=5s --start-period=10s --retries=10 \
    CMD /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P "$MSSQL_SA_PASSWORD" \
        -C \
        -Q "SELECT 1" \
     || exit 1

